version: "3"
services:
  platform-advertiser:
    build: .
    container_name: platform-advertiser
    command: http-server dist
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=platform-advertiser.test
    volumes:
      - .:/var/www/
    tty: true  

      